/**
 * @description       :
 * @author            : pelayochristian.dev@gmail.com
 * @last modified on  : 07-04-2022
 * @last modified by  : pelayochristian.dev@gmail.com
 **/
public with sharing class MW_OpenWeatherController {
    public List<MW_OpenWeather> getCurrentWeatherForecastService(
        Integer longitude,
        Integer latitude,
        Unit unit
    ) {
        return null;
    }
}
